build:
  test:
    image: golang:1.6
    commands:
      - make dependencies
      - make test-coverage
    environment:
      - CONFIG_GOOGLE_SEARCH_CX=$$GOOGLE_SEARCH_CX
      - CONFIG_GOOGLE_SEARCH_KEY=$$GOOGLE_SEARCH_KEY
      - CONFIG_GITHUB_TOKEN=$$GITHUB_TOKEN
      - CONFIG_BING_KEY=$$BING_KEY
  packages:
    image: golang:1.6
    commands:
      - make packages
    when:
      event: tag
  docker_push:
    image: quay.io/srcd/docker-ci
    privileged: true
    commands:
      - make docker-push
    when:
      event: tag

publish:
  github_release:
    api_key: 08763897c930b3ff7f7cebf8da45935350a96b7d
    files: artifacts/*.tar.gz
    when:
      event: tag

compose:
  beanstalkd:
    image: schickling/beanstalkd
  mongodb:
    image: mongo:3.0

notify:
  slack:
    webhook_url: https://hooks.slack.com/services/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
    channel: eng-notifications
    username: drone 
    when:
      success: false
      failure: true
      change: true
